import { WeaponDefinition, ItemType } from "../types/gameTypes";
import { getShieldDefinition } from "./ShieldRegistry";
import { getItemData } from "./ItemRegistry";
import { getContainerData } from "./ContainerRegistry";

export type { WeaponDefinition };

function randBetween(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

const foodData: WeaponDefinition[] = [
  {
    id: "rat_meat",
    name: "item_rat_meat",
    description: "desc_rat_meat",
    damage: 0,
    armor: 0,
    defense: 0,
    cooldown: 0,
    range: 0,
    type: ItemType.FOOD,
    exp_skill: 0,
    weight: 5.0,
    stackable: true,
    consumable: true,
    hungerValue: 60,
  },
];

const weapons: WeaponDefinition[] = [
  {
    id: "wooden_sword",
    name: "item_wooden_sword",
    description: "desc_wooden_sword",
    damage: 8,
    armor: 0,
    defense: 3,
    cooldown: 1000,
    range: 48,
    type: ItemType.SWORD,
    exp_skill: 100,
    weight: 25.0,
    stackable: false,
    consumable: false,
    possibleAttributes: ["melee_crit_chance", "melee_max_damage"],
  },
  {
    id: "torch",
    name: "item_torch",
    description: "desc_torch",
    damage: 1,
    armor: 0,
    defense: 2,
    cooldown: 800,
    range: 40,
    type: ItemType.CLUB,
    exp_skill: 10,
    weight: 15.0,
    stackable: false,
    consumable: false,
    lightRadius: 1200,
  },
  {
    id: "light_torch",
    name: "item_light_torch",
    description: "desc_light_torch",
    damage: 5,
    armor: 0,
    defense: 2,
    cooldown: 800,
    range: 40,
    type: ItemType.CLUB,
    element: "fire",
    lightRadius: 1200,
    exp_skill: 100,
    weight: 15.0,
    stackable: false,
    consumable: false,
  },
  {
    id: "iron_axe",
    name: "item_iron_axe",
    description: "desc_iron_axe",
    damage: 15,
    armor: 0,
    defense: 1,
    cooldown: 1000,
    range: 56,
    type: ItemType.AXE,
    exp_skill: 100,
    weight: 45.0,
    stackable: false,
    consumable: false,
    possibleAttributes: ["melee_crit_chance", "melee_max_damage", "melee_crit_damage"],
  },
  {
    id: "dragon_axe",
    name: "item_dragon_axe",
    description: "desc_dragon_axe",
    damage: 35,
    armor: 0,
    defense: 2,
    cooldown: 1000,
    range: 56,
    type: ItemType.AXE,
    exp_skill: 120,
    weight: 60.0,
    stackable: false,
    consumable: false,
    resistances: { fire: 0.1 },
    defenseResistances: { fire: 0.7 },
    possibleAttributes: ["melee_crit_chance", "melee_max_damage", "melee_crit_damage"],
  },
  {
    id: "short_bow",
    name: "item_short_bow",
    damage: 20,
    armor: 0,
    defense: 0,
    cooldown: 1000,
    range: 400,
    type: ItemType.DISTANCE,
    exp_skill: 100,
    weight: 15.0,
    stackable: false,
    consumable: false,
  },
  {
    id: "throwing_star",
    name: "item_throwing_star",
    damage: 12,
    armor: 0,
    defense: 0,
    cooldown: 600,
    range: 200,
    type: ItemType.DISTANCE,
    exp_skill: 10,
    weight: 2.0,
    stackable: true,
    consumable: true,
  },
  {
    id: "wooden_shield",
    name: "item_wooden_shield",
    description: "desc_wooden_shield",
    damage: 0,
    armor: 0,
    defense: 10,
    cooldown: 0,
    range: 0,
    type: ItemType.SHIELD,
    exp_skill: 100,
    weight: 30.0,
    stackable: false,
    consumable: false,
    resistances: { fire: 0.05 },
    defenseResistances: { fire: -0.8 },
  },
  {
    id: "iron_shield",
    name: "item_iron_shield",
    damage: 0,
    armor: 0,
    defense: 20,
    cooldown: 0,
    range: 0,
    type: ItemType.SHIELD,
    exp_skill: 100,
    weight: 55.0,
    stackable: false,
    consumable: false,
  },
  {
    id: "tower_shield",
    name: "item_tower_shield",
    damage: 0,
    armor: 0,
    defense: 35,
    cooldown: 0,
    range: 0,
    type: ItemType.SHIELD,
    exp_skill: 100,
    weight: 90.0,
    stackable: false,
    consumable: false,
  },
  {
    id: "dragon_shield",
    name: "item_dragon_shield",
    description: "desc_dragon_shield",
    damage: 0,
    armor: 0,
    defense: 38,
    cooldown: 0,
    range: 0,
    type: ItemType.SHIELD,
    exp_skill: 100,
    weight: 65.0,
    stackable: false,
    consumable: false,
  },
  {
    id: "dragon_armor",
    name: "item_dragon_armor",
    description: "desc_dragon_armor",
    damage: 0,
    armor: 14,
    defense: 0,
    cooldown: 0,
    range: 0,
    type: ItemType.BODY_ARMOR,
    exp_skill: 0,
    weight: 100.0,
    stackable: false,
    consumable: false,
  },
  {
    id: "leather_helmet",
    name: "item_leather_helmet",
    damage: 0,
    armor: 2,
    defense: 0,
    cooldown: 0,
    range: 0,
    type: ItemType.HELMET,
    exp_skill: 0,
    weight: 12.0,
    stackable: false,
    consumable: false,
  },
  {
    id: "leather_armor",
    name: "item_leather_armor",
    damage: 0,
    armor: 4,
    defense: 0,
    cooldown: 0,
    range: 0,
    type: ItemType.BODY_ARMOR,
    exp_skill: 0,
    weight: 40.0,
    stackable: false,
    consumable: false,
  },
  {
    id: "leather_legs",
    name: "item_leather_legs",
    damage: 0,
    armor: 2,
    defense: 0,
    cooldown: 0,
    range: 0,
    type: ItemType.LEGS,
    exp_skill: 0,
    weight: 25.0,
    stackable: false,
    consumable: false,
  },
  {
    id: "leather_boots",
    name: "item_leather_boots",
    damage: 0,
    armor: 1,
    defense: 0,
    cooldown: 0,
    range: 0,
    type: ItemType.BOOTS,
    exp_skill: 0,
    weight: 8.0,
    stackable: false,
    consumable: false,
    terrainResistance: 0.5,
  },
  {
    id: "plate_armor",
    name: "item_plate_armor",
    damage: 0,
    armor: 10,
    defense: 0,
    cooldown: 0,
    range: 0,
    type: ItemType.BODY_ARMOR,
    exp_skill: 0,
    weight: 120.0,
    stackable: false,
    consumable: false,
    resistances: { fire: 0.2 },
    defenseResistances: { fire: 0.9 },
  },
  {
    id: "plate_legs",
    name: "item_plate_legs",
    damage: 0,
    armor: 7,
    defense: 0,
    cooldown: 0,
    range: 0,
    type: ItemType.LEGS,
    exp_skill: 0,
    weight: 50.0,
    stackable: false,
    consumable: false,
  },
  {
    id: "iron_helmet",
    name: "item_iron_helmet",
    damage: 0,
    armor: 5,
    defense: 0,
    cooldown: 0,
    range: 0,
    type: ItemType.HELMET,
    exp_skill: 0,
    weight: 30.0,
    stackable: false,
    consumable: false,
  },
  {
    id: "viking_helmet",
    name: "item_viking_helmet",
    damage: 0,
    armor: 4,
    defense: 0,
    cooldown: 0,
    range: 0,
    type: ItemType.HELMET,
    exp_skill: 0,
    weight: 25.0,
    stackable: false,
    consumable: false,
  },
  {
    id: "steel_boots",
    name: "item_steel_boots",
    damage: 0,
    armor: 3,
    defense: 0,
    cooldown: 0,
    range: 0,
    type: ItemType.BOOTS,
    exp_skill: 0,
    weight: 30.0,
    stackable: false,
    consumable: false,
  },
  ...foodData,
];

export function getWeaponDefinition(weaponId: string): WeaponDefinition | undefined {
  const w = weapons.find((w) => w.id === weaponId);
  if (w) return w;

  const food = foodData.find((f) => f.id === weaponId);
  if (food) return food;

  const shield = getShieldDefinition(weaponId);
  if (shield) {
    return {
      id: shield.id,
      name: shield.name,
      defense: shield.defense,
      type: ItemType.SHIELD,
      damage: 0,
      armor: 0,
      cooldown: 0,
      range: 0,
      exp_skill: 0,
      weight: 45.0,
      stackable: false,
      consumable: false,
    };
  }

  const item = getItemData(weaponId);
  if (item) return item;

  const container = getContainerData(weaponId);
  if (container) {
    return {
      id: container.id,
      name: container.name,
      weight: container.weight,
      type: ItemType.CONTAINER,
      damage: 0,
      armor: 0,
      defense: 0,
      cooldown: 0,
      range: 0,
      exp_skill: 0,
      stackable: false,
      consumable: false,
    };
  }

  return undefined;
}

export function getAllWeaponsData(): WeaponDefinition[] {
  return weapons;
}

export const WeaponRegistry = {
  getWeaponDefinition,
  getAllWeaponsData,
  getEquipmentDefinition: getWeaponDefinition,
};
